/**
 *	\file NodeType.h
 *	\brief include a list of terminal/non terminal definitions
 *
 * 	\date Jun 22, 2014
 * 	\author koldar
 *	\version 1.0
 */
#ifndef NODETYPE_H_
#define NODETYPE_H_

typedef enum {
	//Non terminal
	NT_PROGRAM,
	NT_FUNC_DECL,
	NT_DECL_LIST_OPT,
	NT_DECL_LIST,
	NT_DECL,
	NT_ID_LIST,
	NT_DOMAIN,
	NT_ATOMIC_DOMAIN,
	NT_STRUCT_DOMAIN,
	NT_VECTOR_DOMAIN,
	NT_TYPE_SECT_OPT,
	NT_VAR_SECT_OPT,
	NT_CONST_SECT_OPT,
	NT_CONST_DECL_LIST,
	NT_CONST_DECL,
	NT_FUNC_LIST_OPT,
	NT_FUNC_LIST,
	NT_FUNC_BODY,
	NT_STAT_LIST,
	NT_STAT,
	NT_ASSIGN_STAT,
	NT_LEFT_HAND_SIDE,
	NT_IF_STAT,
	NT_ELSIF_STAT_LIST_OPT,
	NT_ELSIF_STAT_LIST,
	NT_ELSE_STAT_OPT,
	NT_WHILE_STAT,
	NT_FOR_STAT,
	NT_FOREACH_STAT,
	NT_RETURN_STAT,
	NT_READ_STAT,
	NT_SPECIFIER_OPT,
	NT_WRITE_STAT,
	NT_EXPR,
	NT_BOOL_TERM_LIST,
	NT_BOOL_OP,
	NT_BOOL_TERM,
	NT_REL_OP,
	NT_REL_TERM,
	NT_LOW_TERM_LIST,
	NT_LOW_BIN_OP,
	NT_LOW_TERM,
	NT_FACTOR_LIST,
	NT_,
	NT_FACTOR,
	NT_UNARY_OP,
	NT_ATOMIC_CONST,
	NT_INSTANCE_CONSTRUCTION,
	NT_STRUCT_CONSTRUCTION,
	NT_EXPR_LIST,
	NT_VECTOR_CONSTRUCTION,
	NT_FUNC_CALL,
	NT_COND_EXPR,
	NT_ELSIF_EXPR_LIST_OPT,
	NT_BUILT_IN_CALL,
	NT_DYNAMIC_INPUT,
	NT_DYNAMIC_OUTPUT,

	//Terminal
	T_INT,
	T_STR,
	T_REAL,
	T_CHAR,
	T_BOOL,
	T_ID

} NodeType;


#endif /* NODETYPE_H_ */
